### ISSUE TITLE
@nuxtjs/markdownit on nuxt3 not working? node 16.14.2

### ISSUE THREAD

**Issue by webdelin** [nuxt-community/markdownit-module#53]
![Bildschirmfoto 2022-03-30 um 12 47 49](https://user-images.githubusercontent.com/21138899/160816700-78b93b4a-a21b-4323-abf6-6f0cd10932de.png)
![Bildschirmfoto 2022-03-30 um 12 49 07](https://user-images.githubusercontent.com/21138899/160816708-4f81d53b-d849-4fc9-ba94-2e0be65c748f.png)
"@nuxtjs/markdownit"
markdownit: { preset: 'default', linkify: true, breaks: true, use: [ 'markdown-it-div', 'markdown-it-attrs' ] },
MyConfig

`import { defineNuxtConfig } from 'nuxt3';
import svgLoader from "vite-svg-loader";
const strapiBaseUri = process.env.API_URL || "http://localhost:1337/";
const baseUrl = process.env.BASE_URL || "http://localhost:3000/";

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
modules: [
['@nuxtjs/strapi',
{
url: strapiBaseUri,
// entities: [
// {
// name: "homepage",
// type: "single",
// },
// {
// name: "global",
// type: "single",
// },
// ],
}],
'@nuxtjs/tailwindcss',
["@nuxtjs/pwa",
{
meta: {
title: "Sitename",
author: "Aes",
},
manifest: {
name: "Sitename",
short_name: "Sitename",
lang: "en",
theme_color: "#721626",
},
}],
["@nuxtjs/sitemap",
{
hostname: baseUrl,
gzip: true,
defaults: {
changefreq: "daily",
priority: 1,
lastmod: new Date(),
},
}],
["@nuxtjs/robots",
{
Sitemap: ${baseUrl}/sitemap.xml,
}], //not working yet
"@aceforth/nuxt-netlify",
"@nuxtjs/device",
"@nuxtjs/markdownit",
],
publicRuntimeConfig: {
strapiBaseUri,
baseUrl,
},
markdownit: {
preset: 'default',
linkify: true,
breaks: true,
use: [
'markdown-it-div',
'markdown-it-attrs'
]
},
vite: {
plugins: [svgLoader()],
},
});
`

**Comment by 984035589** [comment]
encountered the same problem

**Comment by QC2168** [comment]
I also encountered this problem

**Comment by svengau** [comment]
possible solution https://github.com/nuxt-community/markdownit-module/issues/47

**Comment by harlan-zw** [comment]
Will be tracking Nuxt 3 support here https://github.com/nuxt-community/markdownit-module/issues/67
